import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Schibsted_Grotesk} from "next/font/google";

import { cn } from "@/lib/utils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const schibstedGrotesk = Schibsted_Grotesk({
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin", "latin-ext"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('schibstedGrotesk.className text-white')}>{children}</body>
    </html>
  );
}
